#! /bin/sh
set -e

update-alternatives --install /usr/lib/librindowmatrib.so \
                    librindowmatrib.so \
                    /usr/lib/rindowmatrib-serial/libblas.so 90

update-alternatives --install /usr/lib/librindowmatrib.so \
                    librindowmatrib.so \
                    /usr/lib/rindowmatrib-openmp/libblas.so 95



exit 0
