#!/bin/sh
set -e

if [ "$1" != "upgrade" ]
then
    update-alternatives --remove librindowmatrib.so \
                        /usr/lib/rindowmatrib-serial/libblas.so

    update-alternatives --remove librindowmatrib.so \
                        /usr/lib/rindowmatrib-openmp/libblas.so
fi



exit 0
