#!/bin/sh
set -e

if [ "$1" != "upgrade" ]
then
    update-alternatives --remove librindowmatlib.so \
                        /usr/lib/rindowmatlib-serial/librindowmatlib.so

    update-alternatives --remove librindowmatlib.so \
                        /usr/lib/rindowmatlib-openmp/librindowmatlib.so
fi



exit 0
