name: tests

on: 
  push:
    branches:
      - main
  release:
    types:
      - published

jobs:
  build_tests:
    name: build
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        include:
          - name: Windows
            os: windows-latest
            artifact_name: win64.zip
          - name: Linux
            os: ubuntu-latest
            artifact_name: linux.zip
          - name: macOS
            os: macos-latest
            artifact_name: macos.zip
  
    steps:
      - name: Checkout codes
        uses: "actions/checkout@v4"

      - name: Install dependencies (macOS)
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          brew install libomp

      - name: Build
        if: ${{ matrix.os == 'ubuntu-latest' ||  matrix.os == 'windows-latest' }}
        run: |
          cmake -S . -B build && cmake --build build --config Release

      - name: Build (macOS)
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          export OpenMP_ROOT=$(brew --prefix)/opt/libomp
          cmake -S . -B build && cmake --build build --config Release

      - name: GoogleTest Tests
        run: |
          cd build
          ctest -C Release

      - name: Packaging
        run: |
          cd build
          cpack -C Release

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: |
            packages/*

  release:
    needs: [ build_tests ]    
    name: release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v2

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          *.zip
