name: tests

on: 
    push:
        branches:
            - main

jobs:
  build_and_tests:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-latest , macos-latest ]
  
    steps:
      - name: Checkout codes
        uses: "actions/checkout@v4"

      - name: Install dependencies (macOS)
        if: ${{ matrix.os == 'macos-latest' }}
        run: brew install libomp

      - name: Build
        run: cmake -S . -B build && cmake --build build --config Release

      - name: GoogleTest Tests
        run: cd build && ctest

