name: tests

on: 
    push:
        branches:
            - main

jobs:
  build_and_tests:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-latest ]
  
    steps:
      - name: Checkout codes
        uses: "actions/checkout@v4"

      - name: Install dependencies (macOS)
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          brew install libomp

      - name: Build
        if: ${{ matrix.os == 'ubuntu-latest' ||  matrix.os == 'windows-latest' }}
        run: |
          cmake -S . -B build && cmake --build build --config Release

      - name: Build (macOS)
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          export OpenMP_ROOT=$(brew --prefix)/opt/libomp
          cmake -S . -B build && cmake --build build --config Release

      - name: GoogleTest Tests
        run: cd build && ctest

